"""
GATE DOMINION - Project Generator
==================================
AI Role: AI_PROJECT_MANAGER + AI_SYSTEM_ARCHITECT

This script generates the Godot 4.x project file (project.godot)
and ensures the complete folder structure exists.
It is the first step in the automated build pipeline.

Usage:
    python generate_project.py <project_dir> <godot_exe>
"""

import sys
import os


# ============================================================
#  CONFIGURATION
# ============================================================

GAME_NAME = "Gate Dominion"
GAME_VERSION = "0.1.0-prototype"
GAME_DESCRIPTION = "Hybrid RTS + 4X Strategy - AI Generated Prototype"

# Window settings
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
WINDOW_FULLSCREEN = False
WINDOW_RESIZABLE = True
WINDOW_VSYNC = True

# Main scene (entry point)
MAIN_SCENE = "res://scenes/main_menu.tscn"

# Required directories inside the Godot project
PROJECT_DIRS = [
    "scripts",
    "scripts/galaxy",
    "scripts/planet",
    "scripts/units",
    "scripts/structures",
    "scripts/economy",
    "scripts/stargate",
    "scripts/ai_enemy",
    "scripts/core",
    "scripts/camera",
    "scenes",
    "scenes/galaxy",
    "scenes/planet",
    "scenes/units",
    "scenes/structures",
    "ui",
    "ui/menus",
    "ui/hud",
    "data",
    "assets",
    "assets/textures",
    "assets/audio",
    "assets/fonts",
]


# ============================================================
#  PROJECT.GODOT TEMPLATE
# ============================================================

def generate_project_godot():
    """Generate the full contents of project.godot for Godot 4.x."""

    fullscreen_mode = 3 if WINDOW_FULLSCREEN else 0
    vsync_mode = 1 if WINDOW_VSYNC else 0

    return f"""; Engine configuration file.
; Generated by GATE DOMINION AI Build System.
; Do not edit manually.

config_version=5

[application]

config/name="{GAME_NAME}"
config/description="{GAME_DESCRIPTION}"
config/version="{GAME_VERSION}"
run/main_scene="{MAIN_SCENE}"
config/features=PackedStringArray("4.2", "GL Compatibility")
config/icon="res://assets/textures/icon.png"

[autoload]

GameManager="*res://scripts/core/game_manager.gd"
EconomyManager="*res://scripts/economy/economy_manager.gd"
StargateManager="*res://scripts/stargate/stargate_manager.gd"
SaveManager="*res://scripts/core/save_manager.gd"

[display]

window/size/viewport_width={WINDOW_WIDTH}
window/size/viewport_height={WINDOW_HEIGHT}
window/size/resizable={str(WINDOW_RESIZABLE).lower()}
window/size/window_width_override={WINDOW_WIDTH}
window/size/window_height_override={WINDOW_HEIGHT}
window/vsync/vsync_mode={vsync_mode}
window/stretch/mode="canvas_items"
window/stretch/aspect="expand"

[input]

select={{
"deadzone": 0.5,
"events": [Object(InputEventMouseButton,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"button_mask":1,"position":Vector2(0,0),"global_position":Vector2(0,0),"factor":1.0,"button_index":1,"canceled":false,"pressed":true,"double_click":false,"script":null)]
}}

command={{
"deadzone": 0.5,
"events": [Object(InputEventMouseButton,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"button_mask":2,"position":Vector2(0,0),"global_position":Vector2(0,0),"factor":1.0,"button_index":2,"canceled":false,"pressed":true,"double_click":false,"script":null)]
}}

camera_up={{
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":87,"physical_keycode":0,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)]
}}

camera_down={{
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":83,"physical_keycode":0,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)]
}}

camera_left={{
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":65,"physical_keycode":0,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)]
}}

camera_right={{
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":68,"physical_keycode":0,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)]
}}

camera_zoom_in={{
"deadzone": 0.5,
"events": [Object(InputEventMouseButton,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"button_mask":8,"position":Vector2(0,0),"global_position":Vector2(0,0),"factor":1.0,"button_index":4,"canceled":false,"pressed":true,"double_click":false,"script":null)]
}}

camera_zoom_out={{
"deadzone": 0.5,
"events": [Object(InputEventMouseButton,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"button_mask":16,"position":Vector2(0,0),"global_position":Vector2(0,0),"factor":1.0,"button_index":5,"canceled":false,"pressed":true,"double_click":false,"script":null)]
}}

[layer_names]

2d_physics/layer_1="terrain"
2d_physics/layer_2="units_player"
2d_physics/layer_3="units_enemy"
2d_physics/layer_4="structures_player"
2d_physics/layer_5="structures_enemy"
2d_physics/layer_6="projectiles"
2d_physics/layer_7="ui_interaction"

[rendering]

renderer/rendering_method="gl_compatibility"
renderer/rendering_method.mobile="gl_compatibility"
textures/canvas_textures/default_texture_filter=0
"""


# ============================================================
#  ICON GENERATOR (minimal placeholder)
# ============================================================

def generate_placeholder_icon(project_dir):
    """Generate a minimal 64x64 PNG icon as a placeholder.
    Uses raw PNG bytes to avoid external dependencies."""

    import struct
    import zlib

    width = 64
    height = 64

    # Build raw pixel data: simple colored square with border
    rows = []
    for y in range(height):
        row = b""
        for x in range(width):
            # Border (2px dark blue)
            if x < 2 or x >= width - 2 or y < 2 or y >= height - 2:
                row += bytes([20, 30, 80, 255])  # RGBA dark blue
            # Inner "G" letter area (simplified)
            elif 16 <= x <= 48 and 16 <= y <= 48:
                # Draw a rough "G" shape
                in_g = False
                # Top bar
                if 16 <= y <= 20 and 20 <= x <= 44:
                    in_g = True
                # Bottom bar
                elif 44 <= y <= 48 and 20 <= x <= 44:
                    in_g = True
                # Left bar
                elif 16 <= x <= 20 and 16 <= y <= 48:
                    in_g = True
                # Right middle bar
                elif 40 <= x <= 44 and 32 <= y <= 48:
                    in_g = True
                # Middle bar
                elif 32 <= y <= 36 and 32 <= x <= 44:
                    in_g = True

                if in_g:
                    row += bytes([0, 180, 255, 255])  # RGBA cyan
                else:
                    row += bytes([10, 15, 40, 255])  # RGBA dark background
            else:
                row += bytes([10, 15, 40, 255])  # RGBA dark background

        # PNG requires a filter byte at the start of each row
        rows.append(b"\x00" + row)

    raw_data = b"".join(rows)

    # Compress
    compressed = zlib.compress(raw_data)

    # Build PNG file
    def png_chunk(chunk_type, data):
        chunk = chunk_type + data
        crc = struct.pack(">I", zlib.crc32(chunk) & 0xFFFFFFFF)
        return struct.pack(">I", len(data)) + chunk + crc

    png = b"\x89PNG\r\n\x1a\n"  # PNG signature

    # IHDR chunk
    ihdr_data = struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0)
    png += png_chunk(b"IHDR", ihdr_data)

    # IDAT chunk
    png += png_chunk(b"IDAT", compressed)

    # IEND chunk
    png += png_chunk(b"IEND", b"")

    icon_path = os.path.join(project_dir, "assets", "textures", "icon.png")
    with open(icon_path, "wb") as f:
        f.write(png)

    print(f"  Generated placeholder icon: {icon_path}")


# ============================================================
#  EXPORT PRESETS (for Windows build)
# ============================================================

def generate_export_presets(project_dir):
    """Generate export_presets.cfg for Windows desktop build."""

    content = """[preset.0]

name="Windows Desktop"
platform="Windows Desktop"
runnable=true
dedicated_server=false
custom_features=""
export_filter="all_resources"
include_filter=""
exclude_filter=""
export_path="../../build/GateDominion.exe"
encryption_include_filters=""
encryption_exclude_filters=""
encrypt_pck=false
encrypt_directory=false

[preset.0.options]

custom_template/debug=""
custom_template/release=""
debug/export_console_wrapper=1
binary_format/embed_pck=true
texture_format/bptc=true
texture_format/s3tc=true
texture_format/etc=false
texture_format/etc2=false
codesign/enable=false
application/modify_resources=false
application/icon=""
application/console_wrapper_icon=""
application/icon_interpolation=4
application/file_version=""
application/product_version=""
application/company_name="AI Game Studio"
application/product_name="Gate Dominion"
application/file_description="Gate Dominion - Hybrid RTS + 4X Strategy"
application/copyright="Generated by AI"
application/trademarks=""
application/export_angle=0
ssh_remote_deploy/enabled=false
"""

    preset_path = os.path.join(project_dir, "export_presets.cfg")
    with open(preset_path, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"  Generated export presets: {preset_path}")


# ============================================================
#  MAIN ENTRY POINT
# ============================================================

def main():
    if len(sys.argv) < 2:
        print("Usage: python generate_project.py <project_dir> [godot_exe]")
        sys.exit(1)

    project_dir = os.path.abspath(sys.argv[1])
    godot_exe = sys.argv[2] if len(sys.argv) > 2 else None

    print(f"  Project directory: {project_dir}")
    print(f"  Game: {GAME_NAME} v{GAME_VERSION}")
    print()

    # --- Create all directories ---
    print("  Creating project directories...")
    for d in PROJECT_DIRS:
        dir_path = os.path.join(project_dir, d)
        os.makedirs(dir_path, exist_ok=True)
    print(f"  Created {len(PROJECT_DIRS)} directories.")

    # --- Generate project.godot ---
    print("  Generating project.godot...")
    project_file = os.path.join(project_dir, "project.godot")
    with open(project_file, "w", encoding="utf-8") as f:
        f.write(generate_project_godot())
    print(f"  Generated: {project_file}")

    # --- Generate placeholder icon ---
    print("  Generating placeholder icon...")
    generate_placeholder_icon(project_dir)

    # --- Generate export presets ---
    print("  Generating export presets...")
    generate_export_presets(project_dir)

    # --- Generate .gdignore for tools dir (keep tools out of Godot) ---
    gdignore_path = os.path.join(project_dir, ".gdignore")
    # Not needed inside project dir, but ensure we have a clean import

    # --- Create default_env.tres (default environment) ---
    env_content = """[gd_resource type="Environment" format=3]

[resource]
background_mode = 1
background_color = Color(0.05, 0.05, 0.12, 1)
"""
    env_path = os.path.join(project_dir, "default_env.tres")
    with open(env_path, "w", encoding="utf-8") as f:
        f.write(env_content)
    print(f"  Generated: {env_path}")

    # --- Summary ---
    print()
    print("  ========================================")
    print(f"  PROJECT GENERATED: {GAME_NAME}")
    print(f"  Version: {GAME_VERSION}")
    print(f"  Main Scene: {MAIN_SCENE}")
    print(f"  Window: {WINDOW_WIDTH}x{WINDOW_HEIGHT}")
    print("  ========================================")
    print("  Project generation complete.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
